### ISSUE TITLE
Building library needs staged Cargo.lock

### ISSUE THREAD

**Issue by MalteT** [yusdacra/nix-cargo-integration#46] opened 2021-11-07 09:52 UTC
When using this project in a Rust library with flakes, the following error occurs:
```
error: A Cargo.lock file must be present, please make sure it's at least staged in git.
(use '--show-trace' to show detailed location information)
```

This is probably not a problem with nix-cargo-integration, but with the way purity is handled. Is there any workaround other than just staging `Cargo.lock` (and unstaging for every commit)?

Thanks for the awesome work!

**Comment by yusdacra** [comment] 2021-11-07 10:55
Yes, this is intended. I would recommend to just commit the `Cargo.lock` file, since it ensures reproducibility in general. In case of libraries, this might be a problem with CI, but that can be resolved via removing the `Cargo.lock` file before build.

I'm not aware of a workaround that would allow the `Cargo.lock` to be ignored by `git` but still be picked up by Nix (using flakes), as flakes will only pick up files that are at least staged in git.

If you don't want to / can't commit the `Cargo.lock`, one possible option is to make a command that will stage `Cargo.lock`, run `nix build`, and then unstage it, and add it to devshell. That would at least make it less of a headache.

**Comment by bew** [comment] 2021-11-07 11:00
> I'm not aware of a workaround that would allow the Cargo.lock to be ignored by git but still be picked up by Nix (using flakes), as flakes will only pick up files that are at least staged in git.

I know one: `git add -N Cargo.lock` or long form: `git add --intend-to-add Cargo.lock`

It will make the file tracked by git but without staging or committing it

**Comment by MalteT** [comment] 2021-11-07 11:08
> I know one: git add -N Cargo.lock or long form: git add --intend-to-add Cargo.lock
What is this witchery? Works perfectly!

> Yes, this is intended. I would recommend to just commit the Cargo.lock file, since it ensures reproducibility in general. In case of libraries, this might be a problem with CI, but that can be resolved via removing the Cargo.lock file before build.
You're probably right, but the official recommendation is to not do that for libraries, iirc.

@bew's fix works quite well. I guess this can be closed now. Or should there be some documentation about this?

**Comment by yusdacra** [comment] 2021-11-07 13:24
> > I'm not aware of a workaround that would allow the Cargo.lock to be ignored by git but still be picked up by Nix (using flakes), as flakes will only pick up files that are at least staged in git.
> 
> I know one: `git add -N Cargo.lock` or long form: `git add --intend-to-add Cargo.lock`
> 
> It will make the file known by git but without staging or committing it

Oh wow, TIL. From the man page:
```
-N, --intent-to-add
           Record only the fact that the path will be added later. An entry for the path is placed in the index with
           no content. This is useful for, among other things, showing the unstaged content of such files with git
           diff and committing them with git commit -a.
```

Thanks for that!

> bew's fix works quite well. I guess this can be closed now. Or should there be some documentation about this?

Yes, this should be documented. I would appreciate a PR :slightly_smiling_face: We can probably create a "Tips and tricks" or similar section in MANUAL.md, and put it there.

**Closed** 2021-11-07 14:46 UTC
